name: Build and Test App
on: [pull_request]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: v20.14.0
    - run: npm i
  build:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: npm run test:coverage