name: Sync commands for a Discord server
on:
  workflow_dispatch:
    inputs:
      guildId:
        description: 'The id of the target server'
        required: false
        type: string

jobs:
  sync-commands:
    runs-on: ubuntu-latest
    env:
      DEV_GUILD_ID: ${{ secrets.DEV_GUILD_ID }}
      ATARINATOR_CLIENT_ID: ${{ secrets.ATARINATOR_CLIENT_ID }}
      ATARINATOR_TOKEN: ${{ secrets.ATARINATOR_TOKEN }}
      PIKINATOR_CLIENT_ID: ${{ secrets.PIKINATOR_CLIENT_ID }}
      PIKINATOR_TOKEN: ${{ secrets.PIKINATOR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: v20.14.0
      - run: npm i
      - name: Sync
        run: npm run sync -- ${{ inputs.guildId }}